spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grupo5tp
    username: root
    password: root12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
